### ISSUE TITLE
Update Readme file to include setup instructions

### ISSUE THREAD

**Issue by nathan-lapinski** [mikako-shirai/URL-shortening-service#1]
Hello,

I'm excited to install and run this project locally, but the readme does not have any instructions on what to do after I have cloned the repository locally. Could you please update the README file with some instructions on how to install dependencies and run the application, similar to this example?

https://github.com/testdrivenio/django-stripe-checkout#want-to-use-this-project

**Comment by mikako-shirai** [comment]
Resolved #4
